name: beatify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.42
  get: ^4.7.2
  control_style: ^0.1.0
  flip_card: ^0.7.0
  sc_flutter_component_library: ^0.2.0
  file_picker: ^10.3.3
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4   

flutter_launcher_icons:             
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/headphone.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/headphone.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/headphone.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/headphone.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/songs/
    - assets/icons/
